services:
  public-website:
    build:
      context: ${CODE_DIR:-/home/mgps01/mgpsv2/code/mgpsfren/mgps-fenchise-app}
      dockerfile: ${DEPLOY_DIR:-/home/mgps01/mgpsv2/dev/mgps-public}/Dockerfile
    container_name: mgps-public-website
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT:-6079}:80"
