spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mgps_master
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.mgps: INFO
